name: Auto Setup for Student Repos

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup-student-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Skip setup for template repo
        id: check-repo
        run: |
          if [[ "${GITHUB_REPOSITORY}" == "YourOrg/PESU_Template_TaskManager_P01" ]]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            exit 0
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Extract repo info
        if: steps.check-repo.outputs.skip == 'false'
        id: extract
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          IFS='_' read -r PREFIX DEPT COURSE PROJECT SECTION TEAM <<< "$REPO_NAME"
          echo "dept=$DEPT" >> "$GITHUB_OUTPUT"
          echo "course=$COURSE" >> "$GITHUB_OUTPUT"
          echo "project=$PROJECT" >> "$GITHUB_OUTPUT"
          echo "section=$SECTION" >> "$GITHUB_OUTPUT"
          echo "team=$TEAM" >> "$GITHUB_OUTPUT"

      - name: Add topics to repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_ADMIN_TOKEN }}
          script: |
            const topics = [
              'pesu',
              '${{ steps.extract.outputs.dept }}'.toLowerCase(),
              '${{ steps.extract.outputs.course }}'.toLowerCase(),
              '${{ steps.extract.outputs.project }}'.toLowerCase(),
              '${{ steps.extract.outputs.section }}'.toLowerCase(),
              '${{ steps.extract.outputs.team }}'.toLowerCase()
            ];
            await github.repos.replaceAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo,
              names: topics
            });

      - name: Mark setup complete
        run: touch .repo-setup-complete
