name: Setup Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  add-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Repository Info
        id: extract
        run: |
          REPO_NAME="${{ github.event.repository.name }}"

          DEPT=$(echo "$REPO_NAME" | cut -d'_' -f2 | tr '[:upper:]' '[:lower:]')
          COURSE=$(echo "$REPO_NAME" | cut -d'_' -f3 | tr '[:upper:]' '[:lower:]')
          PROJECT=$(echo "$REPO_NAME" | cut -d'_' -f4 | tr '[:upper:]' '[:lower:]')
          SECTION=$(echo "$REPO_NAME" | cut -d'_' -f5 | tr '[:upper:]' '[:lower:]')

          echo "department=$DEPT" >> $GITHUB_OUTPUT
          echo "course=$COURSE" >> $GITHUB_OUTPUT
          echo "project=$PROJECT" >> $GITHUB_OUTPUT
          echo "section=$SECTION" >> $GITHUB_OUTPUT

      - name: Add Topics
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const topics = [
              '${{ steps.extract.outputs.department }}',
              '${{ steps.extract.outputs.course }}',
              '${{ steps.extract.outputs.project }}',
              '${{ steps.extract.outputs.section }}'
            ];

            const repo = context.repo;
            await github.rest.repos.replaceAllTopics({
              owner: repo.owner,
              repo: repo.repo,
              names: topics
            });

            console.log("✅ Topics set: " + topics.join(', '));
